### ISSUE TITLE
Spanish comics are not being updated

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#103]
#91 broke this, I think.

Spanish comics are not listed on this page: https://www.gocomics.com/comics/a-to-z

-----

### Solution

Instead of only scraping a-to-z page for comics, also scrape:
- https://www.gocomics.com/comics/espanol?page=1 and
- https://www.gocomics.com/comics/espanol?page=2

**Comment by yajo** [comment]
Is this the reason why Garfield's last Spanish comic is from December 10, 2018?

**Comment by ArtskydJ** [comment]
yep

**Comment by ArtskydJ** [comment]
> Do a hybrid mix of old detection method and new detection method (awkward code)

No. This would be very annoying to write.

---

> Convince gocomics to include spanish comics in a-to-z page

No. There's a reason they don't include them now.

---

> Instead of only scraping a-to-z page for comics, also scrape [other pages]

**Probably this solution...**

---

> Check for comic-slug-en-espanol for all comic slugs

No. Some are `comicespanol.html`, some are `comic-en-espanol.html`, some are `comicespanol%20.html`.

**Comment by ArtskydJ** [comment]
Fixed. Unfortunately, the backlog of Spanish comic strips was not retrieved.

**Comment by yajo** [comment]
I received updates from Dillbert, but not from Garfield. Is there a specific problem on Garfield?

**Comment by ArtskydJ** [comment]
A long time ago I had made a mistake and made this the rss file for garfield: `comicsrss.com/rss/garfieldespanol%20.rss`
I changed this recently to `comicsrss/rss/garfieldespanol.rss`

I should have made a note in the RSS files themselves.

**Comment by ArtskydJ** [comment]
I added a note now. Please let me know whether you see it in your feed. It should show up within a day.

**Comment by yajo** [comment]
I see no notes, however I already moved to the new one.

I guess the best you can do is just a 301 redirection from the old RSS URL to the new, and remove it from the English section, where it shouldn't be.

**Comment by ArtskydJ** [comment]
I can't do a 301 without switching hosts, cuz I'm using gh-pages right now. :( sorry. I'm trying to fix the note now. I think that's the best I can do without switching hosts.
