### ISSUE TITLE
Some gocomics strips are not showing up

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#107]
From @megadr01d, originally posted in #86 

Hope you don't mind... I removed your other comment since I see these as two separate issues.

-----------------------------------

Why are some GoComics comics are not available?
Like these two, which I'd love to see in the future:

https://www.gocomics.com/how-to-cat
https://www.gocomics.com/redmeat

**Comment by ArtskydJ** [comment]
I don't know why those comics are not available. I thought the program would automatically pick them up. I plan to dig into this when I have time.

**Comment by ghost** [comment]
I don't mind, thanks, and take your time.

**Comment by illinikev** [comment]
Yeah https://www.gocomics.com/peanuts (https://www.comicsrss.com/rss/peanuts.rss) stopped updating on 5/27/2019.

As commented above, take your time.  thanks for the good work.

**Comment by ghost** [comment]
Actually I'm not getting **any** comics for the past 2 days.  I'm gonna try again tonight and report back. Maybe some change in GoComics.

**Comment by ghost** [comment]
@illinikev Created new issue: https://github.com/ArtskydJ/comicsrss.com/issues/108 since this one is about feeds that are available in GoComics but don't show up when searching on www.comicsrss.com. Nothing to do with not updating.

**Comment by illinikev** [comment]
Working again.

Thanks for the fix.

**Comment by ArtskydJ** [comment]
Note that these four comic strips are not working at the moment:
- cats-cafe
- crabgrass
- how-to-cat
- redmeat

**Comment by ghost** [comment]
Thanks for the commit. They're all showing up now.

**Comment by ArtskydJ** [comment]
Whoops, I had forgotten to notify you. Thanks for noticing! :stuck_out_tongue:
