### ISSUE TITLE
 Issues updating feeds

### ISSUE THREAD

**Issue by ghost** [ArtskydJ/comicsrss.com#108]
Split from https://github.com/ArtskydJ/comicsrss.com/issues/107#issuecomment-496990219.
Since 27/05 feeds are not coming through. Today (29/05) only got 2 feeds: Dilbert's 28/05 and 29/05.

**Comment by ArtskydJ** [comment]
I believe this is fixed as of https://github.com/ArtskydJ/comicsrss.com/commit/76fcda8baf760322935442f067d46fd740c207ba. (About 1 hour and 40 minutes ago.)

Re-open this issue if the feeds do not update for you.

**Comment by ArtskydJ** [comment]
Sorry for the delay in this... It happened at an awkward time for me, since I didn't have internet at my house for a while.

**Comment by ghost** [comment]
No apologies necessary, you already do an awesome work. I'm sure we can all go without comics for a week or two. A new issue is just a heads-up, in case you didn't notice it.
