### ISSUE TITLE
Dilbert and Doonesbury last strips from 2019-06-22

### ISSUE THREAD

**Issue by mohawk2** [ArtskydJ/comicsrss.com#110]
Perhaps GoComics changed site?

**Comment by ArtskydJ** [comment]
Actually, I rewrote part of the system, and missed a little bit: https://github.com/ArtskydJ/comicsrss.com/commit/7afbcd53f27613a6a75664b8674503872ef48e48

It should be working now.

**Comment by mohawk2** [comment]
It is! Fine work.
