### ISSUE TITLE
Subject line character encoding

### ISSUE THREAD

**Issue by ghost** [ArtskydJ/comicsrss.com#118]
Recently, the `&` character started to show up as ` &amp;` on email subject lines. The actual title on the message body shows `&` correctly. Probably happens on other non alphanumeric characters too.

Examples

```
Berger &amp; Wyse by Pascal Wyse
WuMo by Wulff &amp; Morgenthaler
Viivi &amp; Wagner by Juba
Sarah&#39;s Scribbles by Sarah Andersen [Edit]
```

**Comment by ArtskydJ** [comment]
Thanks for letting me know. I've fixed it now.
