### ISSUE TITLE
gocomics failed silently on 2020-07-13

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#120]

**Comment by ghost** [comment]
I got Dilbert, don't know how. Every other failed as well.
Also happened once or twice in the past few months and, if memory serves right, always on a Monday.

**Comment by ArtskydJ** [comment]
Dilbert works since it has its own scraper. Dilbert is not pulled from gocomics. The arcamax comics pulled fine too. This seems to be limited to gocomics. My guess is that they changed their site, or had some issue with their site.

I plan to investigate sometime later, if it doesn't fix itself.

**Comment by ghost** [comment]
I think it's probably a temporary issue. Let's see.

**Comment by ghost** [comment]
Just now, I got home and my RSS log had all sorts of 500, 502 and 503 errors for `github.com` feeds, plus some time outs (no `comicsrss.com` errors, tho).
Maybe it was some sort of global content delivery network (CDN) issue which affected Github and GoComics.

**Comment by ArtskydJ** [comment]
Looks like you're onto something...
https://github.com/ArtskydJ/comicsrss.com/blob/gh-pages/rss/calvinandhobbes.rss most recent item is July 13th (today)
https://www.comicsrss.com/rss/calvinandhobbes.rss most recent item is July 12th (yesterday)

**Comment by ArtskydJ** [comment]
Pushing a nothing-commit seems to have fixed the issue for me.

**Comment by ArtskydJ** [comment]
![image](https://user-images.githubusercontent.com/1833684/87345005-fd6cb880-c514-11ea-9964-64c35f49b9aa.png)
That explains it, sorta. Just not sure why the gh-pages push didn't run.

**Comment by ghost** [comment]
Dunno, but I confirm it's fixed. Just got the whole comic bunch right now. :+1:
