### ISSUE TITLE
Feeds Not Updating Since Sept. 9

### ISSUE THREAD

**Issue by jgbishop** [ArtskydJ/comicsrss.com#121]
All feeds seem to have last successfully updated on September 9, 2020. The comics from the past several days have not been pulled in as usual.

**Comment by infinitytec** [comment]
Can confirm. Looking in the XML for the feed shows this.

**Comment by othalan** [comment]
The PR I just submitted should fix the problem (linked above).

**Comment by ArtskydJ** [comment]
Fixed by #122
