### ISSUE TITLE
Arcamax toggles image URLs each hour?

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#126]
https://github.com/ArtskydJ/comicsrss.com/commit/d24fd6abd4c6f14715c3c1752f2cb59df036f773 vs https://github.com/ArtskydJ/comicsrss.com/commit/fc791a699969e2e2f14468740f54e2a18443cee3 has no diffs https://github.com/ArtskydJ/comicsrss.com/compare/2e182a9bfae61722ee2aed156cb37bd6f98612c0...fc791a699969e2e2f14468740f54e2a18443cee3

Every hour it goes back and forth?

It's been doing that for a while.

**Comment by infinitytec** [comment]
Is this why I'm not seeing the comics that come from Arcamax?

**Comment by ArtskydJ** [comment]
> Is this why I'm not seeing the comics that come from Arcamax?

Nope. #129

**Comment by ArtskydJ** [comment]
Considering this fixed in https://github.com/ArtskydJ/comicsrss.com/commit/c71b0b129a861064bb72fc807299189603b578d3
