### ISSUE TITLE
feeds not updating

### ISSUE THREAD

**Issue by infinitytec** [ArtskydJ/comicsrss.com#135]
It looks like there is an error keeping the feeds from updating. It seems that there may be a problem with the Dilbert website.

**Comment by jgbishop** [comment]
None of my feeds are loading, so I'm guessing it's a bigger issue than just Dilbert.

**Comment by infinitytec** [comment]
> None of my feeds are loading, so I'm guessing it's a bigger issue than just Dilbert.

It looks like the Dilbert website is causing the issue though. That's what the logs suggested.

**Comment by jgbishop** [comment]
Ah, interesting. I guess the update process doesn't handle errors properly.

**Comment by dstein766** [comment]
It isn't comicsrss that is at fault.  GoComics is down...and dilbert.com is also.  The latter may be a DNS denial of service (as it no longer resolves to an IP address).  The root of the former isn't yet disclosed.

https://www.dailycartoonist.com/index.php/2022/11/21/gocomics-down-due-to-cybersecurity-issues/

**Comment by infinitytec** [comment]
> It isn't comicsrss that is at fault. GoComics is down...and dilbert.com is also. The latter may be a DNS denial of service (as it no longer resolves to an IP address). The root of the former isn't yet disclosed.
> 
> https://www.dailycartoonist.com/index.php/2022/11/21/gocomics-down-due-to-cybersecurity-issues/

The plot thickens!

**Comment by ArtskydJ** [comment]
Thanks for the bug report.  Just saw this today.  I fixed a couple issues with the error handling:

1. DNS errors don't crash the scraper anymore.
2. If some scrapers succeed, and others fail, then CI will now continue and publish the updates from the scrapers that worked.  It used to not publish anything if any one of the scrapers failed.

You should be seeing updates from https://arcamax.com and https://comicskingdom.com now.  Obviously I can't do anything about https://dilbert.com and https://gocomics.com being down.

**Comment by infinitytec** [comment]
Thanks!

It also looks like everything is back!
