### ISSUE TITLE
Display a better icon for the Source

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#136]
![image](https://user-images.githubusercontent.com/1833684/203387164-b03b530e-3175-465a-83b3-31e8b4c9497e.png)

I want to switch out
![image](https://user-images.githubusercontent.com/1833684/203388457-f7d066b1-a957-4235-945c-94c9b92eb25a.png)
with
<img src="https://www.arcamax.com/favicon.ico" width=16 height=16 /> [Source](https://www.arcamax.com)
and
<img src="https://comicskingdom.com/favicon.ico" width=16 height=16 /> [Source](https://comicskingdom.com)
etc.

**Comment by Thanush19** [comment]
can i fix this??

**Comment by ArtskydJ** [comment]
> can i fix this??

go for it

**Comment by ArtskydJ** [comment]
I still might switch out the link icon for source-specific icons.  It might depend if I pull multiple RSS feeds for each strip in the future in an effort to solve #134.
