### ISSUE TITLE
Add Footer and Header 

### ISSUE THREAD

**Issue by PiyushhBansal** [ArtskydJ/comicsrss.com#144]
i will header and footer in the website. header contain logo name of the website and home about us,  search bar, dark mode . footer contain contact us ,you can find us, email  etc.
Assing this to me under the hacktober label.
<img width="1710" alt="Screenshot 2024-10-12 at 1 57 06 PM" src="https://github.com/user-attachments/assets/ce0ea297-a476-4b88-94ef-574a8259770a">

**Comment by ArtskydJ** [comment]
Thanks for the offer, but I'm not interested.
