### ISSUE TITLE
Wrong feed subject/title

### ISSUE THREAD

**Issue by ghost** [ArtskydJ/comicsrss.com#53]
As of today, 10 dec, feeds arrived with the asset link in place of the subject/title.

![screencap-1512916094092](https://user-images.githubusercontent.com/9649385/33805842-db3509d6-ddb6-11e7-9ca0-3aa7bfe08e15.png)

**Comment by ArtskydJ** [comment]
Thanks for letting me know! I've pushed [a fix](https://github.com/ArtskydJ/comicsrss.com/commit/8f7f7d5ed0abe12b93f60ec0a27831331c1723df) and the files should be re-generated within an hour. Depending on your feed reader, the fix might not show up right away.

**Comment by ghost** [comment]
@ArtskydJ, thanks a lot for the quick fix and for the whole project as it is. I can confirm that it's fixed since I just retrieved new feeds 10 hours after your reply.
