### ISSUE TITLE
Some RSS feeds are not working

### ISSUE THREAD

**Issue by hhobbesg** [ArtskydJ/comicsrss.com#60]
Hello

I just discovered that three RSS feeds do not work. Those are:
- Medical Capsules by Bron Smith
- Garfield in Spanish by Jim Davis
- Ginger Meggs in Spanish by Jason Chatfield

I think the problem is because URLs have a space (%20)

**Comment by ArtskydJ** [comment]
Thank you for reporting this, it is now fixed.
