### ISSUE TITLE
Unable to parse comicsTabRelUrl

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#81]
```
https://www.gocomics.com/1-and-done Unable to parse comicsTabRelUrl
https://www.gocomics.com/2cowsandachicken Unable to parse comicsTabRelUrl
https://www.gocomics.com/9-chickweed-lane-classics Unable to parse comicsTabRelUrl
https://www.gocomics.com/9chickweedlane Unable to parse comicsTabRelUrl
... 551 more
```

**Comment by habi** [comment]
Is that the reason that comicsrss doesn’t work at the moment? Or should I submit a new issue?

**Comment by ghost** [comment]
Having the same question. `rss2email` is not outputting any parsing errors but I'm not getting any feeds.

**Comment by jakewarren** [comment]
Looks like they changed the link that goes to the comics list page so now the regex  https://github.com/ArtskydJ/comicsrss.com/blob/1a64d6d8fd1b3b5c1032b6c8e4d415fa50c9145f/_generator/scraper/get-comic-object.js#L70 isn't matching. 

Here's what I'm getting:
 `<a class="nav-link dropdown-toggle  gc-nav-primary__link" role="button" aria-haspopup="true" aria-expanded="false" data-link-type="banner-nav-tier-1" data-toggle="dropdown" href="https://www.gocomics.com/comics">Find Comics</a>`

**Comment by ArtskydJ** [comment]
Hi all... Sorry about this. I was on a work trip. Yeah, this is the reason the feeds aren't working. I think I've got a fix, and the comics should be up in an hour or two? (The scraper takes a while to run.)

**Comment by habi** [comment]
> Hi all... Sorry about this. I was on a work trip. Yeah, this is the reason the feeds aren't working.
> 
Thanks for fixing it so quickly, the feeds are working again for me.

**Comment by ghost** [comment]
No, we're sorry to bother you on a work trip.
Everything's working fine again. Thanks.

**Comment by ArtskydJ** [comment]
> sorry to bother you on a work trip.

Not a problem.

Glad it's working again.
