### ISSUE TITLE
Add links below comic images?

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#82]
Under the comic image, add links for gocomics, and comicsrss. (And patreon? Not sure about patreon.)

**Comment by ArtskydJ** [comment]
I added the link for gocomics.

**Comment by ghost** [comment]
Suggestion...

You don't need to link the text and the image. The image is just an icon representation of the website in question.
The `p` tags are optional - just to properly format it as a paragraph, so I get the bottom margin after a paragraph, as set in my custom rss2email stylesheet. Feel free to discard if you feel it's better.

```html
<div>
    <p>
        <img src="https://www.comicsrss.com/static/gocomics_sm.png" alt="View on GoComics" style="padding-right: 4px">
        <a href="https://www.gocomics.com/fowl-language/2018/08/30">View on GoComics</a>
    </p>
</div>
```

This is a great project provided for free. I'm sure no one has the right to mind if you post your Patreon and Paypal link as well, but definitely you should also post the link to the source (www.comicrss.com).
