### ISSUE TITLE
Search doesn't work right if you used back button

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#87]
Steps to replicate:
1. Go to https://www.comicsrss.com
2. Type "Calvin"
3. Click one of the comics pages
4. Click the back button

Actual result:
You see the word "Calvin" in the search box, but you see every comic strip in the list

Expected result:
You see the word "Calvin" in the search box, and only the 2 comic strips that have the word "Calvin" in the title.

Related to #80

**Comment by ghost** [comment]
FYI, it works correctly in Safari 11.1.2, OS X 10.11.6. Hitting the back button or using the shortcut key preserves the find results.

**Comment by ArtskydJ** [comment]
Interesting... I got my result on Chrome on Windows...
