### ISSUE TITLE
Not updating, again

### ISSUE THREAD

**Issue by ghost** [ArtskydJ/comicsrss.com#95]
[EDITED]  It **just** updated, a little over 2 hours after the GoComics site updated. 

[ETA]  Except for The Wandering Melon.

**Comment by ghost** [comment]
@SnoManque Just FYI, It's updating fine for me. Got "The Wandering Melon" for November 17, just now.
Also, avoid creating multiple issues for the same problem. Just reopen and reply to the [original](https://github.com/ArtskydJ/comicsrss.com/issues/93) issue. It's good GitHub etiquette.
Cheers.

**Comment by ArtskydJ** [comment]
To keep the discussion in one place, we'll chat in #93 and I'll close this issue. Thanks!
